version: "3.8"

services:
  db:
    image: mysql:8
    container_name: vending-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vending
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 20s

  server:
    build: ./server
    volumes:
      - ./web/web-ui/build:/app/web-build
      - ./swagger.yaml:/app/swagger.yaml
    container_name: vending-server
    env_file:
      - .env
    environment:
      - AGENT_URL=http://client:5000/dispense
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client/agent
    container_name: vending-pi
    ports:
      - "5000:5000"

  machine-ui:
    build:
      context: ./web/machine-ui
      args:
        - NEXT_PUBLIC_OMISE_PUBLIC_KEY=${NEXT_PUBLIC_OMISE_PUBLIC_KEY}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: vending-machine-ui
    ports:
      - "3000:3000"
    depends_on:
      - server
